source "https://rubygems.org"

# Specify your gem's dependencies in sentry-ruby.gemspec
gemspec

# TODO: Remove this if https://github.com/jruby/jruby/issues/6547 is addressed
gem "i18n", "<= 1.8.7"

gem "rake", "~> 12.0"
gem "rspec", "~> 3.0"
gem "codecov", "0.2.12"

gem "delayed_job"
gem "rails"

gem "sentry-ruby", path: "../sentry-ruby"
gem "sentry-rails", path: "../sentry-rails"

gem "pry"
