# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |name| "https://github.com/#{name}.git" }

# Specify your gem's dependencies in sentry-ruby.gemspec
gemspec
gem "sentry-ruby", path: "../sentry-ruby"
gem "sentry-rails", path: "../sentry-rails"

# For https://github.com/ruby/psych/issues/655
gem "psych", "5.1.0"

gem "delayed_job"
gem "delayed_job_active_record"

gem "rails", "> 5.0.0"

platform :jruby do
  # See https://github.com/jruby/activerecord-jdbc-adapter/issues/1139
  gem "activerecord-jdbcmysql-adapter", github: "jruby/activerecord-jdbc-adapter", ref: "6b3983bbbfda75ee2a1f5bc4c8d35efd7b71d84b"
  gem "jdbc-sqlite3"
end

if Gem::Version.new(RUBY_VERSION) < Gem::Version.new("2.5.0")
  gem "sqlite3", "~> 1.3.0", platform: :ruby
else
  gem "sqlite3", "~> 1.6.9", platform: :ruby
end

eval_gemfile File.expand_path("../Gemfile", __dir__)
