source "https://rubygems.org"
git_source(:github) { |name| "https://github.com/#{name}.git" }

# Specify your gem's dependencies in sentry-ruby.gemspec
gemspec
gem "sentry-ruby", path: "../sentry-ruby"
gem "sentry-rails", path: "../sentry-rails"

# For https://github.com/ruby/psych/issues/655
gem "psych", "5.1.0"

gem "rake", "~> 12.0"
gem "rspec", "~> 3.0"
gem 'simplecov'
gem "simplecov-cobertura", "~> 1.4"
gem "rexml"

gem "delayed_job"
gem "delayed_job_active_record"
gem "rails", "> 5.0.0", "< 7.1.0"

platform :jruby do
  gem "activerecord-jdbcmysql-adapter"
  gem "jdbc-sqlite3"
end

gem "sqlite3", platform: :ruby

if RUBY_VERSION.to_f >= 2.6
  gem "debug", github: "ruby/debug", platform: :ruby
  gem "irb"
end

gem "pry"
