minVersion: 2.21.1
changelog:
  policy: auto
preReleaseCommand: ruby .scripts/batch_release.rb
requireNames:
  - /^sentry-ruby-.*\.gem$/
  - /^sentry-ruby-core-.*\.gem$/
  - /^sentry-rails-.*\.gem$/
  - /^sentry-sidekiq-.*\.gem$/
  - /^sentry-resque-.*\.gem$/
  - /^sentry-delayed_job-.*\.gem$/
  - /^sentry-opentelemetry-.*\.gem$/
  - /^sentry-yabeda-.*\.gem$/
targets:
    - name: gem
    - name: registry
      sdks:
        'gem:sentry-ruby':
        'gem:sentry-ruby-core':
        'gem:sentry-rails':
        'gem:sentry-sidekiq':
        'gem:sentry-delayed_job':
        'gem:sentry-opentelemetry':
        'gem:sentry-resque':
        'gem:sentry-yabeda':
          name: 'Sentry Yabeda SDK'
          sdkName: 'sentry.ruby.yabeda'
          packageUrl: 'https://rubygems.org/gems/sentry-yabeda'
          mainDocsUrl: 'https://docs.sentry.io/platforms/ruby/guides/yabeda/'
    - name: github
