minVersion: '0.23.1'
changelogPolicy: simple
preReleaseCommand: ruby .scripts/batch_release.rb
targets:
    - name: gem
    - name: registry
      sdks:
        'gem:sentry-ruby':
        'gem:sentry-ruby-core':
        'gem:sentry-rails':
        'gem:sentry-sidekiq':
        'gem:sentry-delayed_job':
    - name: github
