inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'lib/raven/okjson.rb'
    - 'lib/raven/backports/uri.rb'

Lint/UnusedMethodArgument:
  Exclude:
     - 'lib/raven/backports/uri.rb'

Style/SignalException:
  Enabled: false

Performance/Casecmp:
  Enabled: false
