inherit_gem:
  rubocop-rails-omakase: rubocop.yml

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true

Style/RedundantFreeze:
  Enabled: true

AllCops:
  Exclude:
    - "sentry-raven/**/*"
    - "sentry-*/tmp/**/*"
    - "sentry-*/examples/**/*"
