source "https://rubygems.org"

# Specify your gem's dependencies in sentry-ruby.gemspec
gemspec

gem "sentry-ruby", path: "../sentry-ruby"

# TODO: Remove this if https://github.com/jruby/jruby/issues/6547 is addressed
gem "i18n", "<= 1.8.7"

gem "rake", "~> 12.0"
gem "rspec", "~> 3.0"
gem "rspec-retry"
gem "webmock"
gem "timecop"
gem "codecov", "0.2.12"
gem "tapping_device"

gem "pry"

gem "benchmark-ips"
gem "benchmark_driver"
gem "benchmark-ipsa"
gem "benchmark-memory"
