source "https://rubygems.org"

# Specify your gem's dependencies in sentry-ruby.gemspec
gemspec

gem "rake", "~> 12.0"
gem "rspec", "~> 3.0"
gem "codecov"

gem "pry"
gem "rack"

gem "benchmark-ips"
gem "benchmark_driver"
gem "benchmark-ipsa"
gem "benchmark-memory"
