require "rake/clean"
CLOBBER.include "pkg"

require "bundler/gem_helper"
Bundler::GemHelper.install_tasks(name: "sentry-ruby")

require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec).tap do |task|
  task.rspec_opts = "--order rand"
end

task :default => :spec
