blank_issues_enabled: false
contact_links:
  - name: 📚 SDK Documentation
    url: https://docs.sentry.io/platforms/ruby/
    about: Check the SDK's documentation
    
  - name: 📚 SDK API Documentation
    url: https://www.rubydoc.info/gems/sentry-ruby-core/Sentry
    about: Check the SDK's API documentation

  - name: 💬 Community Discord
    url: https://discord.gg/PXa5Apfe7K
    about: Ping us on Discord if you have questions
