name: Blank Issue
description: Blank Issue. Reserved for maintainers.
labels: ["Ruby"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the issue.
    validations:
      required: true
