source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '> 2.6'

gem "sinatra"

# Use Puma as the app server
gem 'puma', '~> 3.11'

gem 'sentry-ruby', path: "../../"

gem 'pry'
gem "debug", github: "ruby/debug"
