# A test harness for RakeHandler
#
require 'rake'
require 'rubygems'
require 'raven'
require 'raven/rake'

task :raven_raise do
  raise 'test'
end

task :raven_no_raise do
  puts "Only this, and nothing more"
end

module Raven
  def self.capture_exception(exception, options)
    $stderr.puts "[raven] error caught"
  end
end

