require 'rake'
require 'rubygems'
require 'raven'
require 'raven/transports/dummy'

Raven.configure do |config|
  config.dsn = 'dummy://12345:67890@sentry.localdomain/sentry/42'
end

task :raise_exception do
  1 / 0
end
