services:
  sentry-build: &sentry-build
    image: ${DOCKER_IMAGE:-sentry-ruby-devcontainer}:${DOCKER_TAG:-latest}
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE:-ubuntu:24.04}
        RUBY_VERSION: ${RUBY_VERSION:-latest}
    volumes:
      - ..:/workspace/sentry:cached
    working_dir: /workspace/sentry
    env_file: [".env"]

  sentry-dev:
    <<: *sentry-build
    entrypoint: [".devcontainer/run"]
    depends_on:
      - redis

  sentry-test:
    <<: *sentry-build
    profiles: ["e2e"]
    entrypoint: [".devcontainer/run"]
    command: ["mise", "run", "e2e:serve"]
    environment:
      BUNDLE_PATH: /home/sentry/bundle
    volumes:
      - ..:/workspace/sentry:cached
      - bundle-gems:/home/sentry/bundle
    ports:
      - "${SENTRY_E2E_RAILS_APP_PORT}:4000"
      - "${SENTRY_E2E_SVELTE_APP_PORT}:4001"

  redis:
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

volumes:
  bundle-gems:
