source "https://rubygems.org"

# Specify your gem's dependencies in sentry-ruby.gemspec
gemspec

gem "i18n", "~> 1.8.9"

gem "rake", "~> 12.0"
gem "rspec", "~> 3.0"
gem "codecov", "0.2.12"

gem "sidekiq"
gem "rails"

gem "sentry-ruby", path: "../sentry-ruby"
gem "sentry-rails", path: "../sentry-rails"

gem "pry"
