source "https://rubygems.org"
git_source(:github) { |name| "https://github.com/#{name}.git" }

# Specify your gem's dependencies in sentry-ruby.gemspec
gemspec
gem "sentry-ruby", path: "../sentry-ruby"
gem "sentry-rails", path: "../sentry-rails"

gem "rake", "~> 12.0"
gem "rspec", "~> 3.0"
gem 'simplecov'
gem "simplecov-cobertura", "~> 1.4"
gem "rexml"
# https://github.com/flavorjones/loofah/pull/267
# loofah changed the required ruby version in a patch so we need to explicitly pin it
gem "loofah", "2.20.0" if RUBY_VERSION.to_f < 2.5

sidekiq_version = ENV["SIDEKIQ_VERSION"]
sidekiq_version = "7.0" if sidekiq_version.nil?

gem "sidekiq", "~> #{sidekiq_version}"
gem "rails"

ruby_version = Gem::Version.new(RUBY_VERSION)

if ruby_version >= Gem::Version.new("2.6.0")
  gem "debug", github: "ruby/debug", platform: :ruby
  gem "irb"

  if ruby_version >= Gem::Version.new("3.0.0")
    gem "ruby-lsp-rspec"
  end
end

gem "pry"
