source "https://rubygems.org"
git_source(:github) { |name| "https://github.com/#{name}.git" }

# Specify your gem's dependencies in sentry-ruby.gemspec
gemspec

gem "rake", "~> 12.0"
gem "rspec", "~> 3.0"
gem 'simplecov'
gem "simplecov-cobertura", "~> 1.4"
gem "rexml"

sidekiq_version = ENV["SIDEKIQ_VERSION"]
sidekiq_version = "6.0" if sidekiq_version.nil?

gem "rails", "< 7.0"
gem "sidekiq", "~> #{sidekiq_version}"

gem "sentry-ruby", path: "../sentry-ruby"
gem "sentry-rails", path: "../sentry-rails"

gem "object_tracer"
gem "debug", github: "ruby/debug", platform: :ruby if RUBY_VERSION.to_f >= 2.6
gem "pry"

