# frozen_string_literal: true

source 'https://rubygems.org'

gem "rake"
gem "puma"

gem 'railties'
gem 'actionpack'
gem 'activerecord'
gem 'activejob'
gem 'sqlite3'
# Active Support still relies on the JSON 2.x API.
gem 'json', '< 3'

gem 'sentry-ruby', path: '../../..'
gem 'sentry-rails', path: '../../..'
gem 'sidekiq'
gem 'resque'
gem 'delayed_job_active_record'
gem 'solid_queue'
