# frozen_string_literal: true

source "https://rubygems.org"

gem "rails"
gem "sqlite3"
gem "delayed_job"
gem 'delayed_job_active_record'
gem "sentry-delayed_job", path: "../"
gem "sentry-ruby", path: "../../sentry-ruby"

gem "debug", github: "ruby/debug"
