# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |name| "https://github.com/#{name}.git" }

eval_gemfile "../Gemfile.dev"

# Specify your gem's dependencies in sentry-yabeda.gemspec
gemspec

gem "sentry-ruby", path: "../sentry-ruby"

gem "timecop"
