name: Build Release

on:
  push:
    branches:
      - release/**
jobs:
  build:
    name: Build gems
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@319994f95fa847cf3fb3cd3dbe89f6dcde9f178f # v1
      with:
        ruby-version: 3.4
    - name: Build gem source
      run:  ruby .scripts/batch_build.rb
    - name: Archive Artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: ${{ github.sha }}
        path: sentry*/*.gem
