name: Build Release

on:
  push:
    branches:
      - release/**
jobs:
  build:
    name: Build gems
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Set up Ruby
      uses: ruby/setup-ruby@0dafeac902942906541bc140009cdbf32665b601 # v1.315.0
      with:
        ruby-version: 3.4
    - name: Build gem source
      run:  ruby .scripts/batch_build.rb
    - name: Archive Artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: ${{ github.sha }}
        path: sentry*/*.gem
