name: CodeCov

on:
  workflow_run:
    workflows:
      - "sentry-delayed_job Test"
      - "sentry-opentelemetry Test"
      - "sentry-rails Test"
      - "sentry-raven Test"
      - "sentry-resque Test"
      - "sentry-ruby Test"
      - "sentry-sidekiq Test"
    types:
      - completed
    branches:
      - master
    pull_request:
      branches:
        - master

jobs:
  codecov:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Codecov
        uses: codecov/codecov-action@13ce06bfc6bbe3ecf90edbbf1bc32fe5978ca1d3
        run_command: send-notifications
